### ISSUE TITLE
mornin(first gen)への対応について

### ISSUE THREAD

**Issue by sohsatoh** [mugifly/homeassistant-mornin#2]
**したいこと**
mornin(first gen)の操作

**試したこと(gistのスクリプトを使用)**
1. Encryption Keyの取得→成功
2. 各種UUIDの書き換え等

**その他**
以下のエラーが発生します。
mornin+のみ対応ということは理解しているのですが、この場合の対処方法など思いつきましたらお教えいただけると幸いです。(対応できた際にはPull Requestをお送りさせていただきたく思います)

> $ ./morninp.py E4:48:**:**:**:** 67f2f034d7fe4******************* close
>
> Connecting... E4:48:**:**:**:**
> 
> Receiving status... 14010304640700******************
> Generating seed...
> Generating main token... 5c652cb651d4ef*****************
> Generating encrypted main token... 523af387************************
> Trying to authenticate...
> Traceback (most recent call last):
>   File "./morninp.py", line 178, in <module>
>     main()
>   File "./morninp.py", line 169, in main
>     auth_device(peripheral, encrypt_key)
>   File "./morninp.py", line 57, in auth_device
>     app_service_status_characteristic.write(bytes.fromhex(auth_value), True)
>   File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 200, in write
>     return self.peripheral.writeCharacteristic(self.valHandle, val, withResponse)
>   File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 543, in writeCharacteristic
>     return self._getResp('wr')
>   File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 407, in _getResp
>     resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
>   File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 368, in _waitResp
>     raise BTLEGattError("Bluetooth command failed", resp)
> bluepy.btle.BTLEGattError: Bluetooth command failed (code: 3, error: Attribute can't be written)

**Comment by yaman-taku** [comment]
私も同件ついて調査しています。
>Encryption Keyの取得→成功
こちらの方法をご教示いただけないでしょうか？

**Comment by sohsatoh** [comment]
@yaman-taku 単にAndroid appをリバースエンジニアリングしたか、ログを見たかのどちらかだったと記憶しています。(現在他の製品に乗り換えたので記憶が定かではありませんが・・・

**Comment by yaman-taku** [comment]
> @yaman-taku 単にAndroid appをリバースエンジニアリングしたか、ログを見たかのどちらかだったと記憶しています。(現在他の製品に乗り換えたので記憶が定かではありませんが・・・

ありがとうございます！
